# Generated by Django 5.2.7 on 2025-12-05 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('VIDEO', 'Video de YouTube'), ('PDF', 'Material Descargable (PDF)'), ('FORM', 'Simulacro (Google Form)')], max_length=5)),
                ('link', models.URLField(blank=True, help_text='URL para YouTube o Google Forms', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.unit')),
            ],
        ),
    ]
